# Generated by Django 5.0.6 on 2024-11-10 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.CharField(default='Cocktail', max_length=50)),
                ('spirits', models.CharField(default='Spirit', max_length=100)),
                ('taste', models.CharField(default='Taste', max_length=50)),
                ('boozy', models.CharField(default='Boozy', max_length=50)),
                ('ingredients', models.TextField(default='Ingredients')),
                ('instructions', models.TextField(default='Instructions')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/cocktails/')),
            ],
        ),
        migrations.CreateModel(
            name='DrinksMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('rate', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_drinks', to='bar_do_pedro.drinks')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workouts_done', models.IntegerField(default=0)),
                ('latest_post', models.CharField(default="Welcome! Let's drink!", max_length=100)),
                ('spirits', models.CharField(default='Spirits', max_length=100)),
                ('taste', models.CharField(default='Taste', max_length=50)),
                ('boozy', models.CharField(default='Boozy', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
