# Generated by Django 5.0.6 on 2024-11-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinksmade',
            name='cocktail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
