# Generated by Django 5.0.6 on 2024-09-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0003_userprofile_latest_post_delete_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='progress',
        ),
    ]
