# Generated by Django 5.0.6 on 2024-11-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0006_drinks_delete_trainingschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='title',
        ),
        migrations.AddField(
            model_name='drinks',
            name='boozy',
            field=models.CharField(default='Boozy', max_length=50),
        ),
        migrations.AddField(
            model_name='drinks',
            name='cocktail',
            field=models.CharField(default='Cocktail', max_length=50),
        ),
        migrations.AddField(
            model_name='drinks',
            name='spirits',
            field=models.CharField(default='Spirits', max_length=100),
        ),
        migrations.AddField(
            model_name='drinks',
            name='taste',
            field=models.CharField(default='Taste', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latest_post',
            field=models.CharField(default="Welcome! Let's drink!", max_length=100),
        ),
    ]
