# Generated by Django 5.0.6 on 2024-11-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0007_remove_drinks_description_remove_drinks_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='boozy',
            field=models.CharField(default='Boozy', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spirits',
            field=models.CharField(default='Spirits', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='taste',
            field=models.CharField(default='Taste', max_length=50),
        ),
    ]
