# Generated by Django 5.0.6 on 2024-11-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0008_userprofile_boozy_userprofile_spirits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='ingredients',
            field=models.TextField(default='Ingredients'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='instructions',
            field=models.TextField(default='Instructions'),
        ),
    ]
