# Generated by Django 5.0.6 on 2024-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0009_drinks_ingredients_drinks_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinksMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('cocktail', models.CharField(default='Cocktail', max_length=50)),
            ],
        ),
    ]
