# Generated by Django 5.0.6 on 2024-11-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0010_drinksmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinksmade',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drinksmade',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
