# Generated by Django 5.0.6 on 2024-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0011_drinksmade_comment_drinksmade_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinksmade',
            name='rate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
