# Generated by Django 5.0.6 on 2024-11-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_do_pedro', '0015_alter_drinks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cocktails/'),
        ),
    ]
